name: .NET

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true -p:EnableCompressionInSingleFile=true
        zip DotNetBundleExtractor DotNetBundleExtractor/bin/Release/net6.0/win-x64/publish/DotNetBundleExtractor.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          DotNetBundleExtractor.zip
